services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: video_game_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build: ./
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/video_game_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "8081:80"