services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=video_game_store'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'