spring:
  liquibase:
    change-log: db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/video_game_store
    username: postgres
    password: admin
  jpa:
    show-sql: true
    open-in-view: false
  security:
    user:
      name: admin
      password: admin